<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>8f50520f-ea9e-4450-8329-72721926c516</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..\..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.21" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PB.CustomerService.Application\PB.CustomerService.Application.csproj" />
    <ProjectReference Include="..\PB.CustomerService.Infrastructure\PB.CustomerService.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Shared\PB.Shared.Core\PB.Shared.Core.csproj" />
    <ProjectReference Include="..\..\..\Shared\PB.Shared.Messaging\PB.Shared.Messaging.csproj" />
  </ItemGroup>

</Project>
